variable vpc_cidr_block {}
variable subnet_cidr_block {}
variable avail_zone {}
variable env_prefix {}
variable vpc_id {}
variable my_ip {}
variable subnet_id {}
variable image_name {}
variable public_key_location {}
variable security_group_id {}
variable instance_type {}